server.port=80

# DB ??????, ??? password? ????? ????.
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.url=jdbc:mariadb:://aws?ec2?????????/shop?sslMode=trust
spring.datasource.username=admin
spring.datasource.password=????

spring.jpa.properties.hibernate.show_sql=true

spring.jpa.properties.hibernate.format_sql=true

logging.level.org.hibernate.type.descriptor.sql=trace

spring.jpa.hibernate.ddl-auto=create
# spring.jpa.hibernate.ddl-auto=validate? db? ??? ??? ??. create? ????? db ????.
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect

spring.output.ansi.enabled=ALWAYS

spring.thymeleaf.cache = false  

spring.servlet.multipart.maxFileSize=20MB

spring.servlet.multipart.maxRequestSize=100MB

itemImgLocation=/home/ec2-user/shop1/item
uploadPath=file:///home/ec2-user/shop1/

spring.jpa.properties.hibernate.default_batch_fetch_size=1000

naver.client-id=${NAVER_CLIENT_ID}
naver.client-secret=${NAVER_CLIENT_SECRET}
naver.redirect-uri=http://localhost/naver/callback


spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=openid,profile,email


